import { useState } from "react";
import { Scale, Hash, Clock, Shield, Download, Lock, CheckCircle, Link2, AlertTriangle, Inbox } from "lucide-react";
import DashboardLayout from "@/layouts/DashboardLayout";
import { useCases } from "@/contexts/CaseContext";

const downloadBSAReport = (c: any) => {
  const report = `
╔══════════════════════════════════════════════════════════════╗
║          KAVACH DEEPGUARD AI — BSA 2023 COMPLIANT REPORT    ║
║          Bharatiya Sakshya Adhiniyam, 2023                  ║
╚══════════════════════════════════════════════════════════════╝

REPORT ID: BSA-${c.id}
FIR NUMBER: FIR/PB/${new Date().getFullYear()}/${Math.floor(Math.random() * 9999)}
SECTION: BSA 2023 §63 (Electronic Records)
COURT: District Court, Punjab

═══════════════════════════════════════
EVIDENCE DETAILS
═══════════════════════════════════════
File Name: ${c.fileName}
File Size: ${c.fileSize}
File Type: ${c.fileType}

CRYPTOGRAPHIC HASHES:
  Original File SHA-256: ${c.fileHash}
  Analysis Output SHA-256: ${c.analysisHash}

═══════════════════════════════════════
DETECTION SUMMARY
═══════════════════════════════════════
Result: ${c.verdict}
Overall Confidence: ${c.confidence}%
Face Swap Score: ${c.faceSwap}%
Voice Clone Score: ${c.voiceClone}%
Synthetic Artifact Score: ${c.synthetic}%
Severity Classification: ${c.severity.toUpperCase()}
Recommended Action: ${c.action.toUpperCase()}

Model Fingerprint: ${c.fingerprint}
Model Family: ${c.modelFamily}

═══════════════════════════════════════
MANIPULATION TIMESTAMPS
═══════════════════════════════════════
${c.tamperTimestamps.length > 0 ? c.tamperTimestamps.join("\n") : "No manipulation detected"}

═══════════════════════════════════════
CHAIN OF CUSTODY (Hash-Verified)
═══════════════════════════════════════
${c.chainOfCustody.map((e: any) => `[${e.timestamp}] ${e.action}\n  Officer: ${e.officer}\n  Hash: ${e.hash}`).join("\n\n")}

═══════════════════════════════════════
BSA 2023 LEGAL COMPLIANCE
═══════════════════════════════════════
[✓] §63 BSA 2023 — Admissibility of electronic records: COMPLIANT
[✓] §65B BSA 2023 — Certificate for electronic evidence: CERTIFICATE ATTACHED
[✓] IT Act §79A — Central Government notification: COMPLIANT
[✓] Chain of Custody — Unbroken hash-verified custody chain: VERIFIED

═══════════════════════════════════════
CERTIFICATION
═══════════════════════════════════════
This report has been generated by Kavach DeepGuard AI v3.2.1
(build-2024.03.12-stable). The analysis was performed using
certified forensic methodology. All cryptographic hashes have
been verified and the chain of custody is unbroken.

This document is suitable for submission as evidence under
the Bharatiya Sakshya Adhiniyam (BSA), 2023.

Generated: ${c.timestamp}
Report Hash: ${c.analysisHash}
`;

  const blob = new Blob([report], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `BSA_Report_${c.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const Courtroom = () => {
  const { cases } = useCases();
  const [expandedReport, setExpandedReport] = useState<string | null>(cases[0]?.id || null);

  const legalCompliance = [
    { section: "§63 BSA 2023", desc: "Admissibility of electronic records", status: "Compliant" },
    { section: "§65B BSA 2023", desc: "Certificate for electronic evidence", status: "Certificate Attached" },
    { section: "IT Act §79A", desc: "Central Government notification for examiner", status: "Compliant" },
    { section: "Chain of Custody", desc: "Unbroken hash-verified custody chain", status: "Verified" },
  ];

  return (
    <DashboardLayout>
      <div className="space-y-6 animate-fade-in-up">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-foreground">
              <span className="gradient-text">Courtroom</span> Reports
            </h1>
            <p className="text-sm text-muted-foreground mt-1">BSA 2023 compliant · Downloadable · Live from analysis</p>
          </div>
          <div className="flex items-center gap-2">
            <Scale className="w-4 h-4 text-success" />
            <span className="text-xs text-success font-mono">BSA 2023 Certified</span>
          </div>
        </div>

        <div className="glass-card rounded-xl p-4 border-l-4" style={{ borderLeftColor: "hsl(190 100% 50%)" }}>
          <div className="flex items-start gap-3">
            <Scale className="w-5 h-5 text-primary mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-foreground">Bharatiya Sakshya Adhiniyam (BSA), 2023 Compliance</p>
              <p className="text-xs text-muted-foreground mt-1">
                All reports comply with §63, §65B, and IT Act §79A. Reports include cryptographic hash verification, 
                unbroken chain of custody, and certified forensic methodology.
              </p>
            </div>
          </div>
        </div>

        {cases.length === 0 ? (
          <div className="glass-card rounded-xl p-16 text-center">
            <Inbox className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
            <p className="text-foreground font-medium">No court reports yet</p>
            <p className="text-sm text-muted-foreground mt-1">Analyze media to auto-generate BSA 2023 compliant reports</p>
          </div>
        ) : (
          <div className="space-y-4">
            {cases.map(c => {
              const isExpanded = expandedReport === c.id;
              return (
                <div key={c.id} className="glass-card rounded-xl overflow-hidden">
                  <div className="p-5 cursor-pointer" onClick={() => setExpandedReport(isExpanded ? null : c.id)}>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                          <Scale className="w-5 h-5 text-primary" />
                        </div>
                        <div>
                          <p className="text-sm font-semibold text-foreground font-mono">BSA-{c.id}</p>
                          <p className="text-xs text-muted-foreground">{c.fileName} · {c.verdict}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className={`text-xs px-2.5 py-1 rounded-md capitalize ${
                          c.severity === "critical" ? "bg-destructive/20 text-destructive" :
                          c.severity === "suspicious" ? "bg-warning/20 text-warning" :
                          "bg-success/20 text-success"
                        }`}>{c.severity}</span>
                        <button className="p-2 rounded-lg bg-secondary hover:bg-secondary/80 transition-colors" 
                          onClick={e => { e.stopPropagation(); downloadBSAReport(c); }}>
                          <Download className="w-4 h-4 text-foreground" />
                        </button>
                      </div>
                    </div>
                  </div>

                  {isExpanded && (
                    <div className="border-t border-border p-5 space-y-5">
                      {/* Hashes */}
                      <div>
                        <h4 className="text-xs font-semibold text-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                          <Hash className="w-3.5 h-3.5 text-primary" /> Cryptographic Evidence Hashes
                        </h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          <div className="p-3 bg-secondary/50 rounded-lg">
                            <p className="text-xs text-muted-foreground mb-1">Original File SHA-256</p>
                            <p className="font-mono text-xs text-foreground break-all">{c.fileHash}</p>
                          </div>
                          <div className="p-3 bg-secondary/50 rounded-lg">
                            <p className="text-xs text-muted-foreground mb-1">Analysis Output SHA-256</p>
                            <p className="font-mono text-xs text-foreground break-all">{c.analysisHash}</p>
                          </div>
                        </div>
                      </div>

                      {/* Detection */}
                      <div className="p-4 rounded-lg bg-destructive/5 border border-destructive/20">
                        <div className="flex items-center gap-3 mb-3">
                          {c.severity === "critical" ? <AlertTriangle className="w-6 h-6 text-destructive" /> : <CheckCircle className="w-6 h-6 text-success" />}
                          <div>
                            <p className={`text-base font-semibold ${c.severity === "critical" ? "text-destructive" : c.severity === "suspicious" ? "text-warning" : "text-success"}`}>{c.verdict}</p>
                            <p className="text-xs font-mono text-muted-foreground">Confidence: {c.confidence}% · Action: {c.action}</p>
                          </div>
                        </div>
                        <div className="grid grid-cols-3 gap-3">
                          {[{ label: "Face Swap", score: c.faceSwap }, { label: "Voice Clone", score: c.voiceClone }, { label: "Synthetic", score: c.synthetic }].map((s, i) => (
                            <div key={i} className="text-center">
                              <p className="text-xl font-mono font-semibold text-foreground">{s.score}%</p>
                              <p className="text-xs text-muted-foreground">{s.label}</p>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Chain of Custody */}
                      <div>
                        <h4 className="text-xs font-semibold text-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                          <Link2 className="w-3.5 h-3.5 text-primary" /> Chain of Custody
                        </h4>
                        <div className="space-y-0">
                          {c.chainOfCustody.map((entry, i) => (
                            <div key={i} className="flex gap-3 relative">
                              <div className="flex flex-col items-center">
                                <div className="w-3 h-3 rounded-full bg-primary border-2 border-primary/30 z-10" />
                                {i < c.chainOfCustody.length - 1 && <div className="w-0.5 flex-1 bg-border" />}
                              </div>
                              <div className="pb-4">
                                <p className="text-xs font-mono text-muted-foreground">{entry.timestamp}</p>
                                <p className="text-sm text-foreground">{entry.action}</p>
                                <p className="text-xs text-muted-foreground">By: {entry.officer} · Hash: <span className="font-mono text-primary">{entry.hash}</span></p>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Legal Compliance */}
                      <div>
                        <h4 className="text-xs font-semibold text-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                          <Shield className="w-3.5 h-3.5 text-success" /> BSA 2023 Legal Compliance
                        </h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                          {legalCompliance.map((lc, i) => (
                            <div key={i} className="p-3 bg-secondary/50 rounded-lg flex items-center gap-3">
                              <CheckCircle className="w-4 h-4 text-success shrink-0" />
                              <div>
                                <p className="text-xs font-semibold text-foreground">{lc.section}</p>
                                <p className="text-xs text-muted-foreground">{lc.desc}</p>
                              </div>
                              <span className="text-xs text-success font-mono ml-auto whitespace-nowrap">{lc.status}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
};

export default Courtroom;
